title: Zenoi.Chiu
email: hi@qiuzefan.com
description: 邱泽帆个人博客
github_username:  Zeno.Chiu

permalink: /categories/:categories/:year/:month/:day/:title/

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true